package com.app.storitest.ui.theme

import androidx.compose.material3.Typography
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight

val Typography = Typography(
    headlineSmall = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Medium,
        fontSize = HeadlineSmall,
        lineHeight = HeadlineLineHeight,
        color = BlackStori),
    headlineMedium = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Medium,
        fontSize = HeadlineMedium,
        lineHeight = HeadlineLineHeight,
        color = BlackStori),
    headlineLarge = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Bold,
        fontSize = HeadlineLarge,
        lineHeight = HeadlineLineHeight,
        color = BlackStori),
    titleSmall = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Medium,
        fontSize = LabelLarge,
        lineHeight = TitleLineHeight,
        color = BlackStori),
    titleMedium = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Medium,
        fontSize = BodyLarge,
        lineHeight = HeadlineLineHeight,
        color = BlackStori),
    titleLarge = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Bold,
        fontSize = TitleLarge,
        lineHeight = HeadlineLineHeight,
        color = BlackStori),
    bodySmall = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Normal,
        fontSize = LabelMedium,
        lineHeight = BodyLineHeight,
        color = BlackStori),
    bodyMedium = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Normal,
        fontSize = LabelLarge,
        lineHeight = BodyLineHeight,
        color = BlackStori),
    bodyLarge = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Normal,
        fontSize = BodyLarge,
        lineHeight = BodyLineHeight,
        color = BlackStori),
    labelSmall = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Normal,
        fontSize = LabelSmall,
        lineHeight = LabelLineHeight,
        color = BlackStori),
    labelMedium = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Normal,
        fontSize = LabelMedium,
        lineHeight = LabelLineHeight,
        color = BlackStori),
    labelLarge = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Medium,
        fontSize = LabelLarge,
        lineHeight = LabelLineHeight,
        color = BlackStori))